env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  # - plugin:react/recommended
  - plugin:react/jsx-runtime
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  import/extensions: 0
  no-console: 0
  no-unused-vars: 0
  no-param-reassign: 0